### ISSUE TITLE
broken link to integrations

### ISSUE THREAD

**Issue by Danfro** [nymea/nymea-docs#163]
On this page [https://nymea.io/documentation/users/usage/things](https://nymea.io/documentation/users/usage/things) the "integrations" links (two places) is leading to the empty page [https://nymea.io/documentation/overview/integrations](https://nymea.io/documentation/overview/integrations).

I think I saw it somewhere else too but could not find it right now. I will add if I come across it again.

![grafik](https://user-images.githubusercontent.com/37637312/193534569-7ab39ef7-3059-49cd-a970-85b165dad69c.png)

![grafik](https://user-images.githubusercontent.com/37637312/193534711-71a1ee91-49a8-4556-a6cb-c516eac58c3d.png)

**Comment by simonseres** [comment]
Thanks @Danfro  for reporting!
Will be considered in https://github.com/nymea/nymea-docs/pull/164

**Comment by Danfro** [comment]
Cool, thanks for the quick fix.

**Comment by mzanetti** [comment]
fixed and released
